
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:3306/WEBUSERDB?autoreconnect = true
    username: root
    password: mandal01
  application:
    name: user-registration-service

server:
  port: 8081
  
user-search-delete-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 60000
    ReadTimeout: 60000
    ConnectTimeout: 60000
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true    
      
      
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000


