
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:3306/WEBUSERDB?autoreconnect = true
    username: root
    password: mandal01
  application:
    name: user-registation-service

server:
  port: 8081
  
user-search-delete-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
    ReadTimeout: 60000
    ConnectTimeout: 60000
  
  
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://eureka-server:8761/eureka/
    availability-zones:
      region1: zone1
    healthcheck:
      enabled: true
      
      
hystrix:
  command:
    user-registation-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    user-search-delete-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000


